[package]
name = "rust_mongodb"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
chrono = "0.4.37"
futures-util = "0.3.30"
serde = "1.0.197"
dotenv = "0.15.0"
futures = "0.3.28"

[dependencies.mongodb]
version = "3.1.1"
features = ["sync"]